### ISSUE TITLE
Could you provide the info about the format for input data?

### ISSUE THREAD

**Issue by ul611** [pooyafayyaz/Fingerspelling-PoseNet#1]
Hello!

I'm trying to run your code, but I couldn't find all the data in the repository. 
In train_with_lm.py file there is data directory path to MediaPipe results for Chicago dataset.
What kind of file format should I have in this directory?

Maybe you have the code for data preprocessing?

Thanks!

**Comment by pooyafayyaz** [comment]
Hi,
Thank you for your interest in our work. I will share the codes and instructions for pre-processing.

**Comment by pooyafayyaz** [comment]
Hi again @ul611,
Sorry for the delay. The model's input comprises keypoints extracted from MediaPipe, stored in .npy files. Kindly request the dataset and proceed to download it locally. I just pushed the processing code under the name "**extract_pose_mediapipe.py**."

**Comment by ul611** [comment]
Hi, @pooyafayyaz!

Thank you for the code and for the instruction. As I can see, the code is for PHOENIX dataset, but anyway it is useful. If I understand it right, you are creating the numpy array with all the landmarks. I'll try to do the same for Chicago dataset.

**Comment by pooyafayyaz** [comment]
That is just the dataset path. 

It would be exactly the same. It takes the directory of images and run the MediaPipe on them. As you said, it will store the landmarks on numpy array.
